<?php

/**
 * @file
 * Contains nitesh_custom_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nitesh_custom_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nitesh_custom_api module.
    case 'help.page.nitesh_custom_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to add additional field <strong>site API key</strong> in site information form ') . '</p>';
      $output .= '<p>' . t('To set api key go to <a href="../../admin/config/system/site-information">site information form </a> and enter the key in <strong>site API key</strong> field and click on <strong>Update Configuration</strong>') . '</p>';
      $output .= '<p>' . t('This module also give JSON resonse when the API you have entered is passed as url parameter in <strong>/testapikey/{apikey}/{nid}</strong> where <strong>apikey</strong> is the API key you have saved in site information form and <strong>nid</strong> is the node id') . '</p>';
      
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nitesh_custom_api_theme() {
  return [
    'nitesh_custom_api' => [
      'render element' => 'children',
    ],
  ];
}

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() on behalf of nitesh_custom_api.module.
 */
function nitesh_custom_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    // Change form id here
    if ($form_id == 'system_site_information_settings') {
        // drupal_set_message('form_test_form_alter() executed.');
      $siteapikey = '';
      $siteapikey = \Drupal::config('nitesh_custom_api.settings')->get('siteapikey');

        $form['site_information']['siteapikey'] = [
            '#type' => 'textfield',
            '#title' => t('Site API Key'),
            '#description' => t('Enter the API key'),
            '#maxlength' => 64,
            '#size' => 64,
            '#default_value' => $siteapikey,
            '#weight' => '5',
            '#placeholder' => t('Enter API key'),
            ];

        $form['actions']['submit']['#value'] = t('Update Configuration');

        $form['#submit'][] = 'nitesh_custom_api_submit_handler';
    }
}


function nitesh_custom_api_submit_handler(&$form, FormStateInterface $formState) {
  
  if(!empty( $form['site_information']['siteapikey']['#value'] ) 
    && $form['site_information']['siteapikey']['#value'] != \Drupal::config('nitesh_custom_api.settings')->get('siteapikey') ) {

    \Drupal::configFactory()->getEditable('nitesh_custom_api.settings')
      ->set('siteapikey', $form['site_information']['siteapikey']['#value'])
      ->save();
    drupal_set_message('API Key updated to ' . $form['site_information']['siteapikey']['#value']);
  }
}